FROM huggingface/transformers-pytorch-gpu

RUN apt-get update && apt-get install --no-install-recommends -y python3.9 python3.9-dev python3.9-venv python3-pip python3-wheel build-essential && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1

# Install git
RUN apt-get update && apt-get install -y git

# create and activate virtual environment
# using final folder name to avoid path issues with packages
RUN python3.9 -m venv /home/myuser/venv
ENV PATH="/home/myuser/venv/bin:$PATH"

# Install Wheel
RUN pip install wheel

WORKDIR /task

# Install JAX with CUDA. 
# Note: Not sure if this is necessary for the PyTorch version
RUN pip install -U "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

# Clone the specific repo
RUN git clone https://github.com/instadeepai/nucleotide-transformer.git ./nt-terminator && \
    cd ./nt-terminator && \
    pip install . && \
    cd ..

# Copy everything from the current directory into the image
COPY . .

# Install the Python requirements
RUN pip install -r requirements.txt
