FROM --platform=amd64 python:3.10-slim-buster

RUN apt-get clean && \
    apt-get update && \
    apt-get clean

# Install git
RUN apt-get update && apt-get install -y git

WORKDIR /task

# Install Jax with CUDA
RUN pip install -U "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

# Clone the specific repo
RUN git clone https://github.com/instadeepai/nucleotide-transformer.git ./nt-terminator && \
    cd ./nt-terminator && \
    pip install . && \
    cd ..

# Copy everything from the current directory into the image
COPY . .

# Install the Python requirements
RUN pip install -r requirements.txt